# Generated by Django 2.2.2 on 2019-06-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(help_text='Ваше имя?', max_length=20)),
                ('Avatar', models.ImageField(help_text='Фото:', upload_to='media')),
                ('Age', models.PositiveIntegerField(help_text='Возраст?')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
    ]
