# Generated by Django 2.2.2 on 2019-06-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='User_Name',
        ),
    ]
